{
    'name': 'Approval',
    'version': '1.0',
    'summary': 'Approval Management System',
    'description': 'Module for managing approval workflows',
    'author': 'Your Name',
    'website': '',
    'license': 'LGPL-3',
    'category': 'Tools',
    'depends': ['base','mail'],
    'data': [
        'security/ir.model.access.csv',
        'views/approval_history_views.xml',
        'views/approval_history_wizard_views.xml',
    ],
    'demo': [],
    'installable': True,
    'application': False,
    'auto_install': False,
    'external_dependencies': {
        'python': [],
        'bin': [],
    },
    'qweb': [],
    'js': [],
    'css': [],
    'images': [],
    'sequence': 100,
}
